version: "3"
services:
  frontend:
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile
      context: ./docker-prac-fe
    volumes:
      - /usr/app/node_modules
      - ./docker-prac-fe:/usr/app

  backend:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
      context: ./docker-prac-be
    volumes:
      - /usr/app/node_modules
      - ./docker-prac-be:/usr/app

  mysql:
    build:
      dockerfile: Dockerfile
      context: ./docker-prac-mysql
    restart: unless-stopped
    volumes:
      - ./docker-prac-mysql/mysql_data:/var/lib/mysql
      - ./docker-prac-mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: memo_schema

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./docker-prac-nginx
    ports:
      - "3000:80"
    depends_on:
      - frontend

# docker-compose -f docker-compose.yaml up --build -d